[package]
name = "cliCommands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
color-eyre = "0.5"
clap = "4.5.2"
serde = "1.0.197"